# Class-imbalance-aware Deep Learning for Skin Cancer Detection from Lesion Images

**Single-file Google Colab notebook** for a conference-paper style binary skin lesion classification experiment: **benign vs malignant**.

This notebook automatically downloads a Kaggle-hosted ISIC resized dataset, prepares stratified splits, trains EfficientNet and ConvNeXt models with multiple imbalance-aware strategies, evaluates each experiment, saves paper-ready figures/tables, and optionally generates Grad-CAM visualizations.

> Default dataset: `nischaydnk/isic-2019-jpg-224x224-resized`, which contains `train-image/`, `train-metadata.csv`, and a binary `target` column where `0 = benign`, `1 = malignant`.

No experimental results are hard-coded. All results are computed when you run the notebook.

## 1. Install dependencies

Run this cell first. It installs only packages that are usually missing from Colab.

In [1]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
NVIDIA RTX A5000

In [2]:
import sys
print(sys.executable)

/home/22010759/miniconda3/envs/ml/bin/python

In [3]:
import sys
import subprocess
import importlib.util

## 2. Imports, configuration, and reproducibility

For a quick debugging run, set:

```python
CONFIG["run"]["experiment_plan"] = "quick"
CONFIG["dataset"]["max_samples"] = 1000
CONFIG["training"]["epochs"] = 1
```

For paper experiments, use the default `core` plan or switch to `full`.

In [4]:
import os
import json
import math
import random
import shutil
import time
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
from PIL import Image

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
from torch.cuda.amp import autocast, GradScaler

import torchvision.transforms as T
import timm

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    roc_curve,
    precision_recall_curve,
)

import matplotlib.pyplot as plt
import cv2

CONFIG = {
    "project_name": "skin-cancer-class-imbalance",
    "seed": 42,
    "device": "cuda" if torch.cuda.is_available() else "cpu",
    "dataset": {
        "auto_download": True,
        "source": "kagglehub",
        "kaggle_slug": "nischaydnk/isic-2019-jpg-224x224-resized",
        "manual_root": None,
        "csv_path": None,
        "image_dir": None,
        "target_col": "target",
        "image_id_col": None,
        "max_samples": None,
        "test_size": 0.15,
        "val_size": 0.15,
    },
    "training": {
        "image_size": 224,
        "batch_size": 32,
        "num_workers": 2,
        "epochs": 20,
        "learning_rate": 3e-4,
        "weight_decay": 1e-4,
        "early_stopping_patience": 3,
        "threshold": 0.5,
        "use_amp": True,
    },
    "augmentation": {
        "minority_stronger_aug": False,
        "rotation_degrees": 25,
        "color_jitter": {
            "brightness": 0.15,
            "contrast": 0.15,
            "saturation": 0.10,
            "hue": 0.02,
        },
    },
    "loss": {
        "focal_alpha": 0.25,
        "focal_gamma": 2.0,
        "class_balanced_beta": 0.9999,
    },
    "run": {
        "experiment_plan": "core",  # options: quick, core, full
        "save_all_checkpoints": False,
        "make_gradcam": True,
        "continue_on_experiment_error": True,
    },
    "outputs": {
        "root": "content/skin_cancer_outputs",
    },
}

def seed_everything(seed: int = 42) -> None:
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = False
    torch.backends.cudnn.benchmark = True

seed_everything(CONFIG["seed"])
DEVICE = torch.device(CONFIG["device"])
print("Device:", DEVICE)
if DEVICE.type == "cuda":
    print("GPU:", torch.cuda.get_device_name(0))

OUTPUT_ROOT = Path(CONFIG["outputs"]["root"])
CHECKPOINT_DIR = OUTPUT_ROOT / "checkpoints"
LOG_DIR = OUTPUT_ROOT / "logs"
FIGURE_DIR = OUTPUT_ROOT / "figures"
RESULT_DIR = OUTPUT_ROOT / "results"
for d in [CHECKPOINT_DIR, LOG_DIR, FIGURE_DIR, RESULT_DIR]:
    d.mkdir(parents=True, exist_ok=True)

with open(OUTPUT_ROOT / "config_used.json", "w") as f:
    json.dump(CONFIG, f, indent=2)
print("Outputs will be saved to:", OUTPUT_ROOT)

/home/22010759/miniconda3/envs/ml/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Device: cuda
GPU: NVIDIA RTX A5000
Outputs will be saved to: content/skin_cancer_outputs

## 3. Automatic dataset download

The default download uses `kagglehub.dataset_download`. Public Kaggle datasets often download directly. If Kaggle asks for authentication, add `KAGGLE_USERNAME` and `KAGGLE_KEY` to Colab secrets, or upload `kaggle.json` using the fallback code in this cell.

In [5]:
def discover_dataset_files(root: Path) -> Tuple[Path, Path]:
    """Find metadata CSV and image directory automatically."""
    csv_candidates = list(root.rglob("*.csv"))
    if not csv_candidates:
        raise FileNotFoundError(f"No CSV file found under {root}")

    preferred_names = ["train-metadata.csv", "metadata.csv", "train.csv"]
    csv_path = None
    for name in preferred_names:
        matches = [p for p in csv_candidates if p.name.lower() == name]
        if matches:
            csv_path = matches[0]
            break
    if csv_path is None:
        csv_path = csv_candidates[0]

    image_exts = {".jpg", ".jpeg", ".png"}
    image_files = [p for p in root.rglob("*") if p.suffix.lower() in image_exts]
    if not image_files:
        raise FileNotFoundError(f"No image files found under {root}")

    # Prefer a directory called train-image or images if present.
    image_dirs = sorted({p.parent for p in image_files}, key=lambda x: len(str(x)))
    preferred_dir = None
    for dir_name in ["train-image", "train_images", "images", "image"]:
        matches = [d for d in image_dirs if d.name.lower() == dir_name]
        if matches:
            preferred_dir = matches[0]
            break
    if preferred_dir is None:
        # Pick the directory containing the most images.
        counts = {}
        for p in image_files:
            counts[p.parent] = counts.get(p.parent, 0) + 1
        preferred_dir = max(counts, key=counts.get)

    print("Metadata CSV:", csv_path)
    print("Image directory:", preferred_dir)
    return csv_path, preferred_dir

DATASET_ROOT = Path("./content/dataset")
if CONFIG["dataset"].get("csv_path") and CONFIG["dataset"].get("image_dir"):
    CSV_PATH = Path(CONFIG["dataset"]["csv_path"])
    IMAGE_DIR = Path(CONFIG["dataset"]["image_dir"])
else:
    CSV_PATH, IMAGE_DIR = discover_dataset_files(DATASET_ROOT)

print("CSV_PATH =", CSV_PATH)
print("IMAGE_DIR =", IMAGE_DIR)

Metadata CSV: content/dataset/train-metadata.csv
Image directory: content/dataset/image
CSV_PATH = content/dataset/train-metadata.csv
IMAGE_DIR = content/dataset/image

## 4. Dataset preparation and stratified split

This cell resolves image paths, cleans labels, reports class imbalance, and creates stratified train/validation/test splits.

In [6]:
IMAGE_EXTENSIONS = [".jpg", ".jpeg", ".png"]


def infer_target_column(df: pd.DataFrame, preferred: Optional[str] = None) -> str:
    if preferred and preferred in df.columns:
        return preferred
    for col in ["target", "label", "class", "benign_malignant", "diagnosis"]:
        if col in df.columns:
            return col
    raise ValueError(f"Could not infer target column. Columns: {list(df.columns)}")


def convert_binary_target(series: pd.Series) -> pd.Series:
    if pd.api.types.is_numeric_dtype(series):
        return series.astype(float).astype("Int64")
    mapping = {
        "benign": 0,
        "malignant": 1,
        "0": 0,
        "1": 1,
        "false": 0,
        "true": 1,
        "nevus": 0,
        "melanoma": 1,
        "basal cell carcinoma": 1,
        "squamous cell carcinoma": 1,
    }
    return series.astype(str).str.strip().str.lower().map(mapping).astype("Int64")


def build_image_index(image_dir: Path) -> Dict[str, str]:
    image_paths = []
    for ext in IMAGE_EXTENSIONS:
        image_paths.extend(image_dir.rglob(f"*{ext}"))
        image_paths.extend(image_dir.rglob(f"*{ext.upper()}"))
    image_index = {}
    for p in image_paths:
        image_index[p.name] = str(p)
        image_index[p.stem] = str(p)
    print(f"Indexed {len(image_paths):,} image files from {image_dir}")
    return image_index


def infer_image_id_columns(df: pd.DataFrame, preferred: Optional[str] = None) -> List[str]:
    if preferred and preferred in df.columns:
        return [preferred]
    candidates = [
        "image", "image_name", "image_id", "isic_id", "filename", "file_name", "path", "filepath"
    ]
    found = [c for c in candidates if c in df.columns]
    if found:
        return found
    # fallback: try object columns
    return [c for c in df.columns if df[c].dtype == "object"]


def resolve_image_paths(df: pd.DataFrame, image_dir: Path, image_id_col: Optional[str] = None) -> pd.DataFrame:
    image_index = build_image_index(image_dir)
    candidate_cols = infer_image_id_columns(df, image_id_col)
    print("Candidate image id columns:", candidate_cols)

    resolved_paths = []
    resolved_from_col = []
    for _, row in df.iterrows():
        found_path = None
        found_col = None
        for col in candidate_cols:
            val = str(row[col]).strip()
            if val in image_index:
                found_path = image_index[val]
                found_col = col
                break
            stem = Path(val).stem
            if stem in image_index:
                found_path = image_index[stem]
                found_col = col
                break
            for ext in IMAGE_EXTENSIONS:
                candidate = val + ext
                if candidate in image_index:
                    found_path = image_index[candidate]
                    found_col = col
                    break
            if found_path:
                break
        resolved_paths.append(found_path)
        resolved_from_col.append(found_col)

    out = df.copy()
    out["image_path"] = resolved_paths
    out["image_path_source_col"] = resolved_from_col
    missing = out["image_path"].isna().sum()
    if missing > 0:
        print(f"Warning: dropping {missing:,} rows with unresolved image paths.")
        out = out.dropna(subset=["image_path"]).reset_index(drop=True)
    print("Resolved dataframe shape:", out.shape)
    return out


def load_and_prepare_metadata(config: Dict, csv_path: Path, image_dir: Path) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    print("Raw metadata shape:", df.shape)
    print("Columns:", list(df.columns))

    target_col = infer_target_column(df, config["dataset"].get("target_col"))
    df["target"] = convert_binary_target(df[target_col])
    before = len(df)
    df = df.dropna(subset=["target"]).copy()
    df["target"] = df["target"].astype(int)
    df = df[df["target"].isin([0, 1])].copy()
    print(f"Dropped {before - len(df):,} rows with invalid/missing target labels.")

    df = resolve_image_paths(df, image_dir, config["dataset"].get("image_id_col"))

    max_samples = config["dataset"].get("max_samples")
    if max_samples is not None and max_samples < len(df):
        df, _ = train_test_split(
            df,
            train_size=max_samples,
            stratify=df["target"],
            random_state=config["seed"],
        )
        df = df.reset_index(drop=True)
        print(f"Subsampled to {len(df):,} images for debugging.")

    counts = df["target"].value_counts().sort_index()
    print("\nClass distribution:")
    print(counts.rename(index={0: "benign_0", 1: "malignant_1"}))
    if 0 in counts.index and 1 in counts.index:
        print(f"Imbalance ratio benign:malignant = {counts.loc[0] / max(counts.loc[1], 1):.2f}:1")
    return df.reset_index(drop=True)


def make_stratified_splits(df: pd.DataFrame, config: Dict) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    test_size = config["dataset"]["test_size"]
    val_size = config["dataset"]["val_size"]
    seed = config["seed"]

    train_val_df, test_df = train_test_split(
        df,
        test_size=test_size,
        stratify=df["target"],
        random_state=seed,
    )
    relative_val_size = val_size / (1.0 - test_size)
    train_df, val_df = train_test_split(
        train_val_df,
        test_size=relative_val_size,
        stratify=train_val_df["target"],
        random_state=seed,
    )

    train_df = train_df.reset_index(drop=True)
    val_df = val_df.reset_index(drop=True)
    test_df = test_df.reset_index(drop=True)

    for name, split_df in [("train", train_df), ("val", val_df), ("test", test_df)]:
        counts = split_df["target"].value_counts().sort_index().to_dict()
        print(f"{name:>5}: n={len(split_df):,}, class_counts={counts}")
        split_df.to_csv(RESULT_DIR / f"{name}_split.csv", index=False)
    return train_df, val_df, test_df

metadata_df = load_and_prepare_metadata(CONFIG, CSV_PATH, IMAGE_DIR)
train_df, val_df, test_df = make_stratified_splits(metadata_df, CONFIG)

Raw metadata shape: (25331, 4)
Columns: ['Unnamed: 0', 'isic_id', 'patient_id', 'target']
Dropped 0 rows with invalid/missing target labels.
Indexed 25,331 image files from content/dataset/image
Candidate image id columns: ['isic_id']
Resolved dataframe shape: (25331, 6)

Class distribution:
target
benign_0       20809
malignant_1     4522
Name: count, dtype: int64
Imbalance ratio benign:malignant = 4.60:1
train: n=17,731, class_counts={0: 14565, 1: 3166}
  val: n=3,800, class_counts={0: 3122, 1: 678}
 test: n=3,800, class_counts={0: 3122, 1: 678}

## 5. Dataset class and augmentations

The training transform includes resize, flips, rotation, color jitter, tensor conversion, and ImageNet normalization.

In [7]:
IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]


def get_transforms(split: str, config: Dict, stronger: bool = False):
    image_size = config["training"]["image_size"]
    aug_cfg = config["augmentation"]
    jitter = aug_cfg["color_jitter"]

    if split == "train":
        rotation = aug_cfg["rotation_degrees"] * (1.5 if stronger else 1.0)
        brightness = jitter["brightness"] * (1.5 if stronger else 1.0)
        contrast = jitter["contrast"] * (1.5 if stronger else 1.0)
        saturation = jitter["saturation"] * (1.5 if stronger else 1.0)
        hue = min(jitter["hue"] * (1.5 if stronger else 1.0), 0.08)
        return T.Compose([
            T.Resize((image_size, image_size)),
            T.RandomHorizontalFlip(p=0.5),
            T.RandomVerticalFlip(p=0.5),
            T.RandomRotation(degrees=rotation),
            T.ColorJitter(brightness=brightness, contrast=contrast, saturation=saturation, hue=hue),
            T.ToTensor(),
            T.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
        ])

    return T.Compose([
        T.Resize((image_size, image_size)),
        T.ToTensor(),
        T.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
    ])


class SkinLesionDataset(Dataset):
    """Binary skin lesion dataset reading image paths and target labels from a dataframe."""

    def __init__(self, df: pd.DataFrame, transform=None, minority_transform=None):
        self.df = df.reset_index(drop=True).copy()
        self.transform = transform
        self.minority_transform = minority_transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        image_path = row["image_path"]
        target = float(row["target"])
        image = Image.open(image_path).convert("RGB")

        if self.minority_transform is not None and int(target) == 1:
            image = self.minority_transform(image)
        elif self.transform is not None:
            image = self.transform(image)

        target_tensor = torch.tensor(target, dtype=torch.float32)
        return {
            "image": image,
            "target": target_tensor,
            "image_path": image_path,
        }


def make_weighted_sampler(df: pd.DataFrame) -> WeightedRandomSampler:
    targets = df["target"].values.astype(int)
    class_counts = np.bincount(targets, minlength=2)
    class_weights = 1.0 / np.maximum(class_counts, 1)
    sample_weights = class_weights[targets]
    sampler = WeightedRandomSampler(
        weights=torch.DoubleTensor(sample_weights),
        num_samples=len(sample_weights),
        replacement=True,
    )
    return sampler


def make_dataloaders(train_df, val_df, test_df, config: Dict, use_weighted_sampler: bool = False):
    train_transform = get_transforms("train", config)
    minority_transform = None
    if config["augmentation"].get("minority_stronger_aug", False):
        minority_transform = get_transforms("train", config, stronger=True)

    val_transform = get_transforms("val", config)
    train_ds = SkinLesionDataset(train_df, transform=train_transform, minority_transform=minority_transform)
    val_ds = SkinLesionDataset(val_df, transform=val_transform)
    test_ds = SkinLesionDataset(test_df, transform=val_transform)

    sampler = make_weighted_sampler(train_df) if use_weighted_sampler else None
    shuffle = sampler is None

    loader_kwargs = dict(
        batch_size=config["training"]["batch_size"],
        num_workers=config["training"]["num_workers"],
        pin_memory=torch.cuda.is_available(),
    )
    train_loader = DataLoader(train_ds, shuffle=shuffle, sampler=sampler, **loader_kwargs)
    val_loader = DataLoader(val_ds, shuffle=False, **loader_kwargs)
    test_loader = DataLoader(test_ds, shuffle=False, **loader_kwargs)
    return train_loader, val_loader, test_loader

print("Dataset and transform code ready.")

Dataset and transform code ready.

## 6. Models: EfficientNet and ConvNeXt

All models output **one binary logit**. The sigmoid is applied only during metric computation/evaluation.

In [8]:
MODEL_NAME_MAP = {
    "efficientnet_b0": "efficientnet_b0",
    "efficientnet_b3": "efficientnet_b3",
    "convnext_tiny": "convnext_tiny",
}


def build_model(model_key: str, pretrained: bool = True) -> nn.Module:
    if model_key not in MODEL_NAME_MAP:
        raise ValueError(f"Unknown model_key={model_key}. Available: {list(MODEL_NAME_MAP)}")
    model_name = MODEL_NAME_MAP[model_key]
    model = timm.create_model(model_name, pretrained=pretrained, num_classes=1)
    return model


def count_parameters(model: nn.Module) -> int:
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

for key in MODEL_NAME_MAP:
    print(key, "->", MODEL_NAME_MAP[key])

efficientnet_b0 -> efficientnet_b0
efficientnet_b3 -> efficientnet_b3
convnext_tiny -> convnext_tiny

## 7. Loss functions for class imbalance

Implemented losses:

- BCE with logits
- Weighted BCE with `pos_weight = num_negative / num_positive`
- Focal Loss
- Class-Balanced Focal Loss using effective number of samples

In [9]:
class FocalLoss(nn.Module):
    """Binary focal loss over logits."""

    def __init__(self, alpha: float = 0.25, gamma: float = 2.0, reduction: str = "mean"):
        super().__init__()
        self.alpha = alpha
        self.gamma = gamma
        self.reduction = reduction

    def forward(self, logits: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
        logits = logits.view(-1)
        targets = targets.view(-1)
        bce = F.binary_cross_entropy_with_logits(logits, targets, reduction="none")
        probs = torch.sigmoid(logits)
        pt = torch.where(targets == 1, probs, 1 - probs)
        alpha_t = torch.where(
            targets == 1,
            torch.full_like(targets, self.alpha),
            torch.full_like(targets, 1.0 - self.alpha),
        )
        loss = alpha_t * (1 - pt).pow(self.gamma) * bce
        if self.reduction == "mean":
            return loss.mean()
        if self.reduction == "sum":
            return loss.sum()
        return loss


class ClassBalancedFocalLoss(nn.Module):
    """Class-balanced focal loss using effective number of samples."""

    def __init__(self, class_counts: List[int], beta: float = 0.9999, gamma: float = 2.0, reduction: str = "mean"):
        super().__init__()
        if len(class_counts) != 2:
            raise ValueError("Binary classification requires class_counts=[num_negative, num_positive].")
        counts = np.array(class_counts, dtype=np.float64)
        effective_num = 1.0 - np.power(beta, counts)
        weights = (1.0 - beta) / np.maximum(effective_num, 1e-12)
        weights = weights / weights.sum() * 2.0
        self.register_buffer("class_weights", torch.tensor(weights, dtype=torch.float32))
        self.gamma = gamma
        self.reduction = reduction

    def forward(self, logits: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
        logits = logits.view(-1)
        targets = targets.view(-1)
        bce = F.binary_cross_entropy_with_logits(logits, targets, reduction="none")
        probs = torch.sigmoid(logits)
        pt = torch.where(targets == 1, probs, 1 - probs)
        target_long = targets.long()
        alpha_t = self.class_weights[target_long]
        loss = alpha_t * (1 - pt).pow(self.gamma) * bce
        if self.reduction == "mean":
            return loss.mean()
        if self.reduction == "sum":
            return loss.sum()
        return loss


def build_loss(loss_name: str, train_df: pd.DataFrame, config: Dict) -> nn.Module:
    targets = train_df["target"].values.astype(int)
    class_counts = np.bincount(targets, minlength=2)
    num_neg, num_pos = int(class_counts[0]), int(class_counts[1])

    if loss_name == "bce":
        return nn.BCEWithLogitsLoss()

    if loss_name == "weighted_bce":
        pos_weight_value = num_neg / max(num_pos, 1)
        pos_weight = torch.tensor([pos_weight_value], dtype=torch.float32, device=DEVICE)
        print(f"Using weighted BCE pos_weight={pos_weight_value:.4f}")
        return nn.BCEWithLogitsLoss(pos_weight=pos_weight)

    if loss_name == "focal":
        return FocalLoss(
            alpha=config["loss"]["focal_alpha"],
            gamma=config["loss"]["focal_gamma"],
        )

    if loss_name == "class_balanced_focal":
        return ClassBalancedFocalLoss(
            class_counts=[num_neg, num_pos],
            beta=config["loss"]["class_balanced_beta"],
            gamma=config["loss"]["focal_gamma"],
        ).to(DEVICE)

    raise ValueError(f"Unknown loss_name={loss_name}")

print("Loss functions ready.")

Loss functions ready.

## 8. Metrics and plotting utilities

These functions save paper-ready ROC curves, confusion matrices, and training curves.

In [10]:
def compute_metrics(y_true, y_prob, threshold: float = 0.5) -> Dict[str, float]:
    y_true = np.asarray(y_true).astype(int)
    y_prob = np.asarray(y_prob).astype(float)
    y_pred = (y_prob >= threshold).astype(int)

    metrics = {}
    if len(np.unique(y_true)) == 2:
        metrics["roc_auc"] = roc_auc_score(y_true, y_prob)
        metrics["auprc"] = average_precision_score(y_true, y_prob)
    else:
        metrics["roc_auc"] = np.nan
        metrics["auprc"] = np.nan

    metrics["accuracy"] = accuracy_score(y_true, y_pred)
    metrics["precision"] = precision_score(y_true, y_pred, zero_division=0)
    metrics["recall_sensitivity"] = recall_score(y_true, y_pred, zero_division=0)
    metrics["f1"] = f1_score(y_true, y_pred, zero_division=0)

    cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
    tn, fp, fn, tp = cm.ravel()
    metrics["specificity"] = tn / (tn + fp) if (tn + fp) > 0 else 0.0
    metrics["tn"] = int(tn)
    metrics["fp"] = int(fp)
    metrics["fn"] = int(fn)
    metrics["tp"] = int(tp)
    return metrics


def plot_roc_curve(y_true, y_prob, title: str, save_path: Path) -> None:
    y_true = np.asarray(y_true).astype(int)
    y_prob = np.asarray(y_prob).astype(float)
    if len(np.unique(y_true)) < 2:
        print("Skipping ROC curve because only one class is present.")
        return
    fpr, tpr, _ = roc_curve(y_true, y_prob)
    auc_value = roc_auc_score(y_true, y_prob)
    plt.figure(figsize=(6, 5))
    plt.plot(fpr, tpr, label=f"AUC = {auc_value:.4f}")
    plt.plot([0, 1], [0, 1], linestyle="--")
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate / Sensitivity")
    plt.title(title)
    plt.legend(loc="lower right")
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(save_path, dpi=300)
    plt.close()


def plot_confusion_matrix_from_values(y_true, y_prob, threshold: float, title: str, save_path: Path) -> None:
    y_pred = (np.asarray(y_prob) >= threshold).astype(int)
    cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
    plt.figure(figsize=(5, 4))
    plt.imshow(cm, interpolation="nearest")
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(2)
    plt.xticks(tick_marks, ["benign", "malignant"], rotation=30)
    plt.yticks(tick_marks, ["benign", "malignant"])
    thresh = cm.max() / 2.0 if cm.max() > 0 else 0.5
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            plt.text(j, i, format(cm[i, j], "d"), ha="center", va="center",
                     color="white" if cm[i, j] > thresh else "black")
    plt.ylabel("True label")
    plt.xlabel("Predicted label")
    plt.tight_layout()
    plt.savefig(save_path, dpi=300)
    plt.close()


def plot_training_curves(log_df: pd.DataFrame, title: str, save_path: Path) -> None:
    plt.figure(figsize=(8, 5))
    plt.plot(log_df["epoch"], log_df["train_loss"], label="train_loss")
    plt.plot(log_df["epoch"], log_df["val_loss"], label="val_loss")
    if "val_roc_auc" in log_df.columns:
        plt.plot(log_df["epoch"], log_df["val_roc_auc"], label="val_roc_auc")
    plt.xlabel("Epoch")
    plt.ylabel("Value")
    plt.title(title)
    plt.legend()
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(save_path, dpi=300)
    plt.close()


def plot_combined_roc(results: List[Dict], save_path: Path) -> None:
    plt.figure(figsize=(7, 6))
    plotted = 0
    for r in results:
        pred_path = r.get("test_predictions_path")
        if not pred_path or not Path(pred_path).exists():
            continue
        pred_df = pd.read_csv(pred_path)
        y_true = pred_df["target"].values.astype(int)
        y_prob = pred_df["probability"].values.astype(float)
        if len(np.unique(y_true)) < 2:
            continue
        fpr, tpr, _ = roc_curve(y_true, y_prob)
        auc_value = roc_auc_score(y_true, y_prob)
        label = f"{r['experiment_name']} (AUC={auc_value:.3f})"
        plt.plot(fpr, tpr, label=label)
        plotted += 1
    if plotted == 0:
        plt.close()
        return
    plt.plot([0, 1], [0, 1], linestyle="--")
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate / Sensitivity")
    plt.title("Test ROC comparison")
    plt.legend(fontsize=7, loc="lower right")
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(save_path, dpi=300)
    plt.close()

print("Metric and plotting utilities ready.")

Metric and plotting utilities ready.

## 9. Training and evaluation loops

Best checkpoint is selected by validation ROC-AUC. If AUC cannot be computed, F1 is used as a fallback score.

In [11]:
def run_one_epoch(model, loader, criterion, optimizer=None, scaler=None, config: Dict = CONFIG):
    is_train = optimizer is not None
    model.train(is_train)
    losses = []
    all_targets = []
    all_probs = []
    all_paths = []

    for batch in loader:
        images = batch["image"].to(DEVICE, non_blocking=True)
        targets = batch["target"].to(DEVICE, non_blocking=True)

        if is_train:
            optimizer.zero_grad(set_to_none=True)

        use_amp = config["training"].get("use_amp", True) and DEVICE.type == "cuda"
        with torch.set_grad_enabled(is_train):
            with autocast(enabled=use_amp):
                logits = model(images).view(-1)
                loss = criterion(logits, targets)

            if is_train:
                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()

        probs = torch.sigmoid(logits.detach()).cpu().numpy()
        losses.append(loss.item() * images.size(0))
        all_targets.extend(targets.detach().cpu().numpy().tolist())
        all_probs.extend(probs.tolist())
        all_paths.extend(batch["image_path"])

    avg_loss = float(np.sum(losses) / len(loader.dataset))
    metrics = compute_metrics(all_targets, all_probs, threshold=config["training"]["threshold"])
    return avg_loss, metrics, np.array(all_targets), np.array(all_probs), all_paths


def evaluate_model(model, loader, criterion, config: Dict = CONFIG):
    with torch.no_grad():
        return run_one_epoch(model, loader, criterion, optimizer=None, scaler=None, config=config)


def experiment_score(metrics: Dict[str, float]) -> float:
    auc = metrics.get("roc_auc", np.nan)
    if auc is not None and np.isfinite(auc):
        return float(auc)
    return float(metrics.get("f1", 0.0))


def train_experiment(exp: Dict, train_df, val_df, test_df, config: Dict = CONFIG) -> Dict:
    seed_everything(config["seed"])
    experiment_name = exp["name"]
    print("\n" + "=" * 90)
    print("Starting experiment:", experiment_name)
    print(exp)

    train_loader, val_loader, test_loader = make_dataloaders(
        train_df, val_df, test_df, config, use_weighted_sampler=exp.get("weighted_sampler", False)
    )

    model = build_model(exp["model_key"], pretrained=exp.get("pretrained", True)).to(DEVICE)
    print(f"Trainable parameters: {count_parameters(model):,}")

    criterion = build_loss(exp["loss_name"], train_df, config)
    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=config["training"]["learning_rate"],
        weight_decay=config["training"]["weight_decay"],
    )
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=max(config["training"]["epochs"], 1)
    )
    scaler = GradScaler(enabled=config["training"].get("use_amp", True) and DEVICE.type == "cuda")

    best_score = -float("inf")
    best_epoch = -1
    epochs_without_improvement = 0
    log_rows = []
    best_ckpt_path = CHECKPOINT_DIR / f"{experiment_name}_best.pt"

    for epoch in range(1, config["training"]["epochs"] + 1):
        start = time.time()
        train_loss, train_metrics, _, _, _ = run_one_epoch(
            model, train_loader, criterion, optimizer=optimizer, scaler=scaler, config=config
        )
        val_loss, val_metrics, _, _, _ = evaluate_model(model, val_loader, criterion, config=config)
        scheduler.step()

        score = experiment_score(val_metrics)
        improved = score > best_score
        if improved:
            best_score = score
            best_epoch = epoch
            epochs_without_improvement = 0
            torch.save({
                "model_state_dict": model.state_dict(),
                "experiment": exp,
                "config": config,
                "best_epoch": best_epoch,
                "best_score": best_score,
                "val_metrics": val_metrics,
            }, best_ckpt_path)
        else:
            epochs_without_improvement += 1

        row = {
            "experiment_name": experiment_name,
            "epoch": epoch,
            "train_loss": train_loss,
            "val_loss": val_loss,
            "train_roc_auc": train_metrics["roc_auc"],
            "train_auprc": train_metrics["auprc"],
            "train_accuracy": train_metrics["accuracy"],
            "train_f1": train_metrics["f1"],
            "val_roc_auc": val_metrics["roc_auc"],
            "val_auprc": val_metrics["auprc"],
            "val_accuracy": val_metrics["accuracy"],
            "val_precision": val_metrics["precision"],
            "val_recall_sensitivity": val_metrics["recall_sensitivity"],
            "val_specificity": val_metrics["specificity"],
            "val_f1": val_metrics["f1"],
            "lr": optimizer.param_groups[0]["lr"],
            "epoch_seconds": time.time() - start,
            "improved": improved,
        }
        log_rows.append(row)
        print(
            f"Epoch {epoch:03d} | "
            f"train_loss={train_loss:.4f} | val_loss={val_loss:.4f} | "
            f"val_auc={val_metrics['roc_auc']:.4f} | "
            f"val_sens={val_metrics['recall_sensitivity']:.4f} | "
            f"val_spec={val_metrics['specificity']:.4f} | "
            f"val_f1={val_metrics['f1']:.4f} | "
            f"best_epoch={best_epoch}"
        )

        if epochs_without_improvement >= config["training"]["early_stopping_patience"]:
            print(f"Early stopping at epoch {epoch}.")
            break

    log_df = pd.DataFrame(log_rows)
    log_path = LOG_DIR / f"{experiment_name}_training_log.csv"
    log_df.to_csv(log_path, index=False)
    plot_training_curves(log_df, experiment_name, FIGURE_DIR / f"{experiment_name}_training_curves.png")

    # Load best checkpoint and evaluate test set.
    checkpoint = torch.load(best_ckpt_path, map_location=DEVICE, weights_only=False)
    model.load_state_dict(checkpoint["model_state_dict"])
    test_loss, test_metrics, y_true, y_prob, paths = evaluate_model(model, test_loader, criterion, config=config)

    pred_df = pd.DataFrame({
        "image_path": paths,
        "target": y_true.astype(int),
        "probability": y_prob.astype(float),
        "prediction": (y_prob >= config["training"]["threshold"]).astype(int),
    })
    pred_path = RESULT_DIR / f"{experiment_name}_test_predictions.csv"
    pred_df.to_csv(pred_path, index=False)

    plot_roc_curve(y_true, y_prob, f"ROC - {experiment_name}", FIGURE_DIR / f"{experiment_name}_roc.png")
    plot_confusion_matrix_from_values(
        y_true,
        y_prob,
        config["training"]["threshold"],
        f"Confusion Matrix - {experiment_name}",
        FIGURE_DIR / f"{experiment_name}_confusion_matrix.png",
    )

    result = {
        "experiment_name": experiment_name,
        "model_key": exp["model_key"],
        "loss_name": exp["loss_name"],
        "weighted_sampler": exp.get("weighted_sampler", False),
        "best_epoch": best_epoch,
        "best_val_score": best_score,
        "test_loss": test_loss,
        "test_predictions_path": str(pred_path),
        "checkpoint_path": str(best_ckpt_path),
        "log_path": str(log_path),
    }
    for k, v in test_metrics.items():
        result[f"test_{k}"] = v

    print("Test metrics:")
    for k in ["roc_auc", "auprc", "accuracy", "precision", "recall_sensitivity", "specificity", "f1"]:
        print(f"  {k}: {test_metrics[k]:.4f}")
    return result

print("Training functions ready.")

Training functions ready.

## 10. Experiment plan

`core` runs the minimum set needed to answer the paper's research questions. `full` adds EfficientNet-B3 comparisons.

In [12]:
def get_experiments(plan: str) -> List[Dict]:
    quick = [
        {"name": "effb0_bce_quick", "model_key": "efficientnet_b0", "loss_name": "bce", "weighted_sampler": False, "pretrained": True},
    ]

    core = [
        {"name": "effb0_bce", "model_key": "efficientnet_b0", "loss_name": "bce", "weighted_sampler": False, "pretrained": True},
        {"name": "effb0_weighted_bce", "model_key": "efficientnet_b0", "loss_name": "weighted_bce", "weighted_sampler": False, "pretrained": True},
        {"name": "effb0_focal", "model_key": "efficientnet_b0", "loss_name": "focal", "weighted_sampler": False, "pretrained": True},
        {"name": "effb0_cb_focal", "model_key": "efficientnet_b0", "loss_name": "class_balanced_focal", "weighted_sampler": False, "pretrained": True},
        {"name": "effb0_weighted_bce_sampler", "model_key": "efficientnet_b0", "loss_name": "weighted_bce", "weighted_sampler": True, "pretrained": True},
        {"name": "convnext_tiny_bce", "model_key": "convnext_tiny", "loss_name": "bce", "weighted_sampler": False, "pretrained": True},
        {"name": "convnext_tiny_weighted_bce", "model_key": "convnext_tiny", "loss_name": "weighted_bce", "weighted_sampler": False, "pretrained": True},
        {"name": "convnext_tiny_focal", "model_key": "convnext_tiny", "loss_name": "focal", "weighted_sampler": False, "pretrained": True},
        {"name": "convnext_tiny_cb_focal", "model_key": "convnext_tiny", "loss_name": "class_balanced_focal", "weighted_sampler": False, "pretrained": True},
        {"name": "convnext_tiny_weighted_bce_sampler", "model_key": "convnext_tiny", "loss_name": "weighted_bce", "weighted_sampler": True, "pretrained": True},
    ]

    full_extra = [
        {"name": "effb3_weighted_bce", "model_key": "efficientnet_b3", "loss_name": "weighted_bce", "weighted_sampler": False, "pretrained": True},
        {"name": "effb3_cb_focal", "model_key": "efficientnet_b3", "loss_name": "class_balanced_focal", "weighted_sampler": False, "pretrained": True},
        {"name": "effb3_weighted_bce_sampler", "model_key": "efficientnet_b3", "loss_name": "weighted_bce", "weighted_sampler": True, "pretrained": True},
    ]

    if plan == "quick":
        return quick
    if plan == "core":
        return core
    if plan == "full":
        return core + full_extra
    raise ValueError(f"Unknown experiment plan: {plan}")

EXPERIMENTS = get_experiments(CONFIG["run"]["experiment_plan"])
print(f"Experiment plan = {CONFIG['run']['experiment_plan']} | n={len(EXPERIMENTS)}")
for exp in EXPERIMENTS:
    print("-", exp["name"])

Experiment plan = core | n=10
- effb0_bce
- effb0_weighted_bce
- effb0_focal
- effb0_cb_focal
- effb0_weighted_bce_sampler
- convnext_tiny_bce
- convnext_tiny_weighted_bce
- convnext_tiny_focal
- convnext_tiny_cb_focal
- convnext_tiny_weighted_bce_sampler

## 11. Run all experiments

This cell trains all configured experiments and saves logs, checkpoints, figures, and predictions.

In [13]:
all_results = []
failed_experiments = []

for exp in EXPERIMENTS:
    try:
        result = train_experiment(exp, train_df, val_df, test_df, CONFIG)
        all_results.append(result)
        summary_df = pd.DataFrame(all_results)
        summary_df.to_csv(RESULT_DIR / "all_experiments_summary_partial.csv", index=False)
    except Exception as e:
        print(f"Experiment failed: {exp['name']}")
        print(repr(e))
        failed_experiments.append({"experiment_name": exp["name"], "error": repr(e)})
        if not CONFIG["run"].get("continue_on_experiment_error", True):
            raise

summary_df = pd.DataFrame(all_results)
summary_path = RESULT_DIR / "all_experiments_summary.csv"
summary_df.to_csv(summary_path, index=False)

if failed_experiments:
    failed_df = pd.DataFrame(failed_experiments)
    failed_df.to_csv(RESULT_DIR / "failed_experiments.csv", index=False)
    print("Failed experiments saved to:", RESULT_DIR / "failed_experiments.csv")

plot_combined_roc(all_results, FIGURE_DIR / "combined_test_roc.png")
print("\nFinal summary saved to:", summary_path)
summary_df

==========================================================================================
Starting experiment: effb0_bce
{'name': 'effb0_bce', 'model_key': 'efficientnet_b0', 'loss_name': 'bce', 'weighted_sampler': False, 'pretrained': True}
Trainable parameters: 4,008,829

/tmp/ipykernel_1467851/2574245648.py:73: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler(enabled=config["training"].get("use_amp", True) and DEVICE.type == "cuda")
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 001 | train_loss=0.6432 | val_loss=0.3381 | val_auc=0.8503 | val_sens=0.3923 | val_spec=0.9654 | val_f1=0.5057 | best_epoch=1

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 002 | train_loss=0.3223 | val_loss=0.3106 | val_auc=0.8830 | val_sens=0.3746 | val_spec=0.9846 | val_f1=0.5184 | best_epoch=2

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 003 | train_loss=0.2864 | val_loss=0.2843 | val_auc=0.8954 | val_sens=0.4735 | val_spec=0.9773 | val_f1=0.6000 | best_epoch=3

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 004 | train_loss=0.2633 | val_loss=0.2697 | val_auc=0.9096 | val_sens=0.5841 | val_spec=0.9603 | val_f1=0.6611 | best_epoch=4

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 005 | train_loss=0.2301 | val_loss=0.2779 | val_auc=0.9142 | val_sens=0.5855 | val_spec=0.9606 | val_f1=0.6628 | best_epoch=5

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 006 | train_loss=0.2149 | val_loss=0.3111 | val_auc=0.9051 | val_sens=0.5767 | val_spec=0.9545 | val_f1=0.6457 | best_epoch=5

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 007 | train_loss=0.1921 | val_loss=0.2692 | val_auc=0.9194 | val_sens=0.5708 | val_spec=0.9632 | val_f1=0.6559 | best_epoch=7

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 008 | train_loss=0.1684 | val_loss=0.2547 | val_auc=0.9310 | val_sens=0.6637 | val_spec=0.9516 | val_f1=0.7037 | best_epoch=8

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 009 | train_loss=0.1505 | val_loss=0.2996 | val_auc=0.9228 | val_sens=0.6077 | val_spec=0.9628 | val_f1=0.6833 | best_epoch=8

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 010 | train_loss=0.1211 | val_loss=0.2831 | val_auc=0.9358 | val_sens=0.5870 | val_spec=0.9747 | val_f1=0.6892 | best_epoch=10

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 011 | train_loss=0.0989 | val_loss=0.3090 | val_auc=0.9363 | val_sens=0.7124 | val_spec=0.9488 | val_f1=0.7313 | best_epoch=11

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 012 | train_loss=0.0829 | val_loss=0.2836 | val_auc=0.9390 | val_sens=0.6947 | val_spec=0.9536 | val_f1=0.7280 | best_epoch=12

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 013 | train_loss=0.0656 | val_loss=0.3070 | val_auc=0.9402 | val_sens=0.6799 | val_spec=0.9568 | val_f1=0.7237 | best_epoch=13

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 014 | train_loss=0.0480 | val_loss=0.3558 | val_auc=0.9369 | val_sens=0.6962 | val_spec=0.9529 | val_f1=0.7278 | best_epoch=13

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 015 | train_loss=0.0357 | val_loss=0.3478 | val_auc=0.9437 | val_sens=0.6652 | val_spec=0.9744 | val_f1=0.7461 | best_epoch=15

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 016 | train_loss=0.0289 | val_loss=0.3452 | val_auc=0.9440 | val_sens=0.7153 | val_spec=0.9574 | val_f1=0.7485 | best_epoch=16

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 017 | train_loss=0.0269 | val_loss=0.3548 | val_auc=0.9450 | val_sens=0.7021 | val_spec=0.9673 | val_f1=0.7580 | best_epoch=17

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 018 | train_loss=0.0181 | val_loss=0.3487 | val_auc=0.9458 | val_sens=0.7183 | val_spec=0.9606 | val_f1=0.7562 | best_epoch=18

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 019 | train_loss=0.0161 | val_loss=0.3576 | val_auc=0.9464 | val_sens=0.7316 | val_spec=0.9622 | val_f1=0.7678 | best_epoch=19

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 020 | train_loss=0.0155 | val_loss=0.3545 | val_auc=0.9473 | val_sens=0.6976 | val_spec=0.9657 | val_f1=0.7520 | best_epoch=20

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Test metrics:
  roc_auc: 0.9573
  auprc: 0.8717
  accuracy: 0.9279
  precision: 0.8412
  recall_sensitivity: 0.7345
  specificity: 0.9699
  f1: 0.7843

==========================================================================================
Starting experiment: effb0_weighted_bce
{'name': 'effb0_weighted_bce', 'model_key': 'efficientnet_b0', 'loss_name': 'weighted_bce', 'weighted_sampler': False, 'pretrained': True}
Trainable parameters: 4,008,829
Using weighted BCE pos_weight=4.6004

/tmp/ipykernel_1467851/2574245648.py:73: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler(enabled=config["training"].get("use_amp", True) and DEVICE.type == "cuda")
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 001 | train_loss=1.6191 | val_loss=0.8590 | val_auc=0.8416 | val_sens=0.5855 | val_spec=0.8780 | val_f1=0.5453 | best_epoch=1

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 002 | train_loss=0.8753 | val_loss=0.8584 | val_auc=0.8594 | val_sens=0.5693 | val_spec=0.9055 | val_f1=0.5681 | best_epoch=2

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 003 | train_loss=0.7284 | val_loss=0.6901 | val_auc=0.8965 | val_sens=0.6799 | val_spec=0.8962 | val_f1=0.6302 | best_epoch=3

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 004 | train_loss=0.6711 | val_loss=0.6385 | val_auc=0.9068 | val_sens=0.7847 | val_spec=0.8482 | val_f1=0.6318 | best_epoch=4

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 005 | train_loss=0.5626 | val_loss=0.6676 | val_auc=0.9074 | val_sens=0.7684 | val_spec=0.8674 | val_f1=0.6460 | best_epoch=5

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 006 | train_loss=0.5181 | val_loss=0.6328 | val_auc=0.9135 | val_sens=0.8658 | val_spec=0.7867 | val_f1=0.6080 | best_epoch=6

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 007 | train_loss=0.4881 | val_loss=0.6181 | val_auc=0.9169 | val_sens=0.8392 | val_spec=0.8286 | val_f1=0.6386 | best_epoch=7

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 008 | train_loss=0.4273 | val_loss=0.6436 | val_auc=0.9186 | val_sens=0.8555 | val_spec=0.8174 | val_f1=0.6346 | best_epoch=8

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 009 | train_loss=0.4184 | val_loss=0.7329 | val_auc=0.9161 | val_sens=0.7625 | val_spec=0.8930 | val_f1=0.6763 | best_epoch=8

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 010 | train_loss=0.3487 | val_loss=0.7848 | val_auc=0.9198 | val_sens=0.7419 | val_spec=0.9158 | val_f1=0.6967 | best_epoch=10

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 011 | train_loss=0.2997 | val_loss=0.6590 | val_auc=0.9340 | val_sens=0.8407 | val_spec=0.8674 | val_f1=0.6859 | best_epoch=11

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 012 | train_loss=0.2329 | val_loss=0.7975 | val_auc=0.9288 | val_sens=0.7876 | val_spec=0.9068 | val_f1=0.7106 | best_epoch=11

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 013 | train_loss=0.2081 | val_loss=0.7482 | val_auc=0.9316 | val_sens=0.8097 | val_spec=0.9013 | val_f1=0.7153 | best_epoch=11

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 014 | train_loss=0.1628 | val_loss=0.8334 | val_auc=0.9373 | val_sens=0.7906 | val_spec=0.9260 | val_f1=0.7419 | best_epoch=14

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 015 | train_loss=0.1240 | val_loss=0.9214 | val_auc=0.9405 | val_sens=0.7817 | val_spec=0.9398 | val_f1=0.7593 | best_epoch=15

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 016 | train_loss=0.1040 | val_loss=0.8230 | val_auc=0.9442 | val_sens=0.8333 | val_spec=0.9177 | val_f1=0.7533 | best_epoch=16

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 017 | train_loss=0.0830 | val_loss=0.9553 | val_auc=0.9426 | val_sens=0.7950 | val_spec=0.9331 | val_f1=0.7560 | best_epoch=16

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 018 | train_loss=0.0658 | val_loss=0.9453 | val_auc=0.9434 | val_sens=0.8024 | val_spec=0.9340 | val_f1=0.7619 | best_epoch=16

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 019 | train_loss=0.0609 | val_loss=0.9919 | val_auc=0.9444 | val_sens=0.7935 | val_spec=0.9446 | val_f1=0.7747 | best_epoch=19

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 020 | train_loss=0.0574 | val_loss=1.0341 | val_auc=0.9466 | val_sens=0.7847 | val_spec=0.9484 | val_f1=0.7761 | best_epoch=20

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Test metrics:
  roc_auc: 0.9576
  auprc: 0.8696
  accuracy: 0.9245
  precision: 0.7896
  recall_sensitivity: 0.7861
  specificity: 0.9545
  f1: 0.7879

==========================================================================================
Starting experiment: effb0_focal
{'name': 'effb0_focal', 'model_key': 'efficientnet_b0', 'loss_name': 'focal', 'weighted_sampler': False, 'pretrained': True}
Trainable parameters: 4,008,829

/tmp/ipykernel_1467851/2574245648.py:73: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler(enabled=config["training"].get("use_amp", True) and DEVICE.type == "cuda")
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 001 | train_loss=0.1816 | val_loss=0.0396 | val_auc=0.8069 | val_sens=0.1136 | val_spec=0.9949 | val_f1=0.1997 | best_epoch=1

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 002 | train_loss=0.0427 | val_loss=0.0393 | val_auc=0.8535 | val_sens=0.0973 | val_spec=0.9994 | val_f1=0.1769 | best_epoch=2

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 003 | train_loss=0.0505 | val_loss=0.0376 | val_auc=0.8538 | val_sens=0.1195 | val_spec=0.9997 | val_f1=0.2132 | best_epoch=3

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 004 | train_loss=0.0356 | val_loss=0.0355 | val_auc=0.8724 | val_sens=0.1799 | val_spec=0.9987 | val_f1=0.3035 | best_epoch=4

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 005 | train_loss=0.0319 | val_loss=0.1441 | val_auc=0.8759 | val_sens=0.2950 | val_spec=0.9824 | val_f1=0.4287 | best_epoch=5

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 006 | train_loss=0.0306 | val_loss=0.0314 | val_auc=0.8728 | val_sens=0.3230 | val_spec=0.9910 | val_f1=0.4735 | best_epoch=5

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 007 | train_loss=0.0292 | val_loss=0.0302 | val_auc=0.8966 | val_sens=0.3776 | val_spec=0.9849 | val_f1=0.5219 | best_epoch=7

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 008 | train_loss=0.0297 | val_loss=0.0297 | val_auc=0.8997 | val_sens=0.4012 | val_spec=0.9849 | val_f1=0.5456 | best_epoch=8

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 009 | train_loss=0.0272 | val_loss=0.0410 | val_auc=0.8910 | val_sens=0.2124 | val_spec=0.9958 | val_f1=0.3449 | best_epoch=8

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 010 | train_loss=0.0275 | val_loss=0.0311 | val_auc=0.9003 | val_sens=0.2640 | val_spec=0.9968 | val_f1=0.4129 | best_epoch=10

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 011 | train_loss=0.0256 | val_loss=0.0271 | val_auc=0.9159 | val_sens=0.4764 | val_spec=0.9821 | val_f1=0.6112 | best_epoch=11

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 012 | train_loss=0.0225 | val_loss=0.0267 | val_auc=0.9146 | val_sens=0.4646 | val_spec=0.9869 | val_f1=0.6093 | best_epoch=11

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 013 | train_loss=0.0208 | val_loss=0.0265 | val_auc=0.9232 | val_sens=0.4661 | val_spec=0.9859 | val_f1=0.6089 | best_epoch=13

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 014 | train_loss=0.0190 | val_loss=0.0290 | val_auc=0.9231 | val_sens=0.4307 | val_spec=0.9910 | val_f1=0.5852 | best_epoch=13

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 015 | train_loss=0.0165 | val_loss=0.0286 | val_auc=0.9217 | val_sens=0.4322 | val_spec=0.9904 | val_f1=0.5854 | best_epoch=13

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 016 | train_loss=0.0154 | val_loss=0.0276 | val_auc=0.9287 | val_sens=0.5177 | val_spec=0.9865 | val_f1=0.6555 | best_epoch=16

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 017 | train_loss=0.0127 | val_loss=0.0300 | val_auc=0.9288 | val_sens=0.5870 | val_spec=0.9769 | val_f1=0.6934 | best_epoch=17

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 018 | train_loss=0.0118 | val_loss=0.0319 | val_auc=0.9310 | val_sens=0.6106 | val_spec=0.9699 | val_f1=0.6981 | best_epoch=18

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 019 | train_loss=0.0106 | val_loss=0.0365 | val_auc=0.9283 | val_sens=0.5914 | val_spec=0.9734 | val_f1=0.6902 | best_epoch=18

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 020 | train_loss=0.0102 | val_loss=0.0461 | val_auc=0.9308 | val_sens=0.5900 | val_spec=0.9792 | val_f1=0.6999 | best_epoch=18

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Test metrics:
  roc_auc: 0.9391
  auprc: 0.8216
  accuracy: 0.9105
  precision: 0.8407
  recall_sensitivity: 0.6150
  specificity: 0.9747
  f1: 0.7104

==========================================================================================
Starting experiment: effb0_cb_focal
{'name': 'effb0_cb_focal', 'model_key': 'efficientnet_b0', 'loss_name': 'class_balanced_focal', 'weighted_sampler': False, 'pretrained': True}
Trainable parameters: 4,008,829

/tmp/ipykernel_1467851/2574245648.py:73: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler(enabled=config["training"].get("use_amp", True) and DEVICE.type == "cuda")
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 001 | train_loss=0.4579 | val_loss=0.2714 | val_auc=0.7750 | val_sens=0.3702 | val_spec=0.9132 | val_f1=0.4183 | best_epoch=1

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 002 | train_loss=0.0958 | val_loss=0.0901 | val_auc=0.8656 | val_sens=0.4690 | val_spec=0.9465 | val_f1=0.5469 | best_epoch=2

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 003 | train_loss=0.1112 | val_loss=0.0778 | val_auc=0.8747 | val_sens=0.5560 | val_spec=0.9315 | val_f1=0.5942 | best_epoch=3

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 004 | train_loss=0.0941 | val_loss=0.3117 | val_auc=0.8124 | val_sens=0.5678 | val_spec=0.8632 | val_f1=0.5168 | best_epoch=3

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 005 | train_loss=0.0764 | val_loss=0.0707 | val_auc=0.8933 | val_sens=0.7124 | val_spec=0.8748 | val_f1=0.6224 | best_epoch=5

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 006 | train_loss=0.0701 | val_loss=0.0691 | val_auc=0.8962 | val_sens=0.7301 | val_spec=0.8652 | val_f1=0.6211 | best_epoch=6

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 007 | train_loss=0.0669 | val_loss=0.0686 | val_auc=0.9020 | val_sens=0.7301 | val_spec=0.8789 | val_f1=0.6383 | best_epoch=7

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 008 | train_loss=0.0690 | val_loss=0.0710 | val_auc=0.9067 | val_sens=0.8392 | val_spec=0.7988 | val_f1=0.6069 | best_epoch=8

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 009 | train_loss=0.0632 | val_loss=0.0724 | val_auc=0.9014 | val_sens=0.7021 | val_spec=0.9007 | val_f1=0.6503 | best_epoch=8

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 010 | train_loss=0.0549 | val_loss=0.0774 | val_auc=0.9122 | val_sens=0.6327 | val_spec=0.9462 | val_f1=0.6729 | best_epoch=10

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 011 | train_loss=0.0558 | val_loss=0.0686 | val_auc=0.9164 | val_sens=0.7566 | val_spec=0.8908 | val_f1=0.6697 | best_epoch=11

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 012 | train_loss=0.0461 | val_loss=0.0757 | val_auc=0.9176 | val_sens=0.7419 | val_spec=0.9049 | val_f1=0.6806 | best_epoch=12

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 013 | train_loss=0.0460 | val_loss=0.0727 | val_auc=0.9273 | val_sens=0.7537 | val_spec=0.9167 | val_f1=0.7053 | best_epoch=13

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 014 | train_loss=0.0374 | val_loss=0.0820 | val_auc=0.9239 | val_sens=0.6947 | val_spec=0.9363 | val_f1=0.6988 | best_epoch=13

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 015 | train_loss=0.0300 | val_loss=0.0807 | val_auc=0.9282 | val_sens=0.7611 | val_spec=0.9170 | val_f1=0.7103 | best_epoch=15

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 016 | train_loss=0.0292 | val_loss=0.0855 | val_auc=0.9298 | val_sens=0.7257 | val_spec=0.9308 | val_f1=0.7100 | best_epoch=16

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 017 | train_loss=0.0226 | val_loss=0.0914 | val_auc=0.9357 | val_sens=0.7375 | val_spec=0.9398 | val_f1=0.7321 | best_epoch=17

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 018 | train_loss=0.0200 | val_loss=0.0885 | val_auc=0.9366 | val_sens=0.7714 | val_spec=0.9318 | val_f1=0.7397 | best_epoch=18

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 019 | train_loss=0.0190 | val_loss=0.0963 | val_auc=0.9352 | val_sens=0.7448 | val_spec=0.9369 | val_f1=0.7319 | best_epoch=18

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 020 | train_loss=0.0183 | val_loss=0.0945 | val_auc=0.9363 | val_sens=0.7463 | val_spec=0.9417 | val_f1=0.7408 | best_epoch=18

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Test metrics:
  roc_auc: 0.9393
  auprc: 0.8303
  accuracy: 0.9024
  precision: 0.7123
  recall_sensitivity: 0.7596
  specificity: 0.9334
  f1: 0.7352

==========================================================================================
Starting experiment: effb0_weighted_bce_sampler
{'name': 'effb0_weighted_bce_sampler', 'model_key': 'efficientnet_b0', 'loss_name': 'weighted_bce', 'weighted_sampler': True, 'pretrained': True}
Trainable parameters: 4,008,829
Using weighted BCE pos_weight=4.6004

/tmp/ipykernel_1467851/2574245648.py:73: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler(enabled=config["training"].get("use_amp", True) and DEVICE.type == "cuda")
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 001 | train_loss=1.8823 | val_loss=1.0972 | val_auc=0.8364 | val_sens=0.9027 | val_spec=0.5333 | val_f1=0.4456 | best_epoch=1

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 002 | train_loss=0.8699 | val_loss=0.8345 | val_auc=0.8751 | val_sens=0.8982 | val_spec=0.6547 | val_f1=0.5150 | best_epoch=2

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 003 | train_loss=0.6847 | val_loss=0.6796 | val_auc=0.9071 | val_sens=0.8333 | val_spec=0.8145 | val_f1=0.6202 | best_epoch=3

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 004 | train_loss=0.5973 | val_loss=0.8576 | val_auc=0.8957 | val_sens=0.8997 | val_spec=0.6957 | val_f1=0.5451 | best_epoch=3

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 005 | train_loss=0.5174 | val_loss=0.6962 | val_auc=0.9177 | val_sens=0.8525 | val_spec=0.8312 | val_f1=0.6483 | best_epoch=5

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 006 | train_loss=0.4582 | val_loss=0.7223 | val_auc=0.9192 | val_sens=0.8732 | val_spec=0.7857 | val_f1=0.6106 | best_epoch=6

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 007 | train_loss=0.3887 | val_loss=0.6872 | val_auc=0.9200 | val_sens=0.8289 | val_spec=0.8632 | val_f1=0.6743 | best_epoch=7

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 008 | train_loss=0.3328 | val_loss=0.6678 | val_auc=0.9289 | val_sens=0.8673 | val_spec=0.8386 | val_f1=0.6644 | best_epoch=8

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 009 | train_loss=0.3013 | val_loss=0.7162 | val_auc=0.9246 | val_sens=0.8555 | val_spec=0.8370 | val_f1=0.6565 | best_epoch=8

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 010 | train_loss=0.2381 | val_loss=0.7696 | val_auc=0.9305 | val_sens=0.8407 | val_spec=0.8603 | val_f1=0.6770 | best_epoch=10

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 011 | train_loss=0.1859 | val_loss=0.7732 | val_auc=0.9284 | val_sens=0.8009 | val_spec=0.8857 | val_f1=0.6882 | best_epoch=10

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 012 | train_loss=0.1629 | val_loss=0.7316 | val_auc=0.9448 | val_sens=0.8274 | val_spec=0.9078 | val_f1=0.7348 | best_epoch=12

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 013 | train_loss=0.1238 | val_loss=0.8422 | val_auc=0.9398 | val_sens=0.8009 | val_spec=0.9113 | val_f1=0.7250 | best_epoch=12

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 014 | train_loss=0.1246 | val_loss=0.7755 | val_auc=0.9465 | val_sens=0.8171 | val_spec=0.9212 | val_f1=0.7497 | best_epoch=14

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 015 | train_loss=0.0762 | val_loss=0.7865 | val_auc=0.9480 | val_sens=0.8260 | val_spec=0.9247 | val_f1=0.7604 | best_epoch=15

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 016 | train_loss=0.0581 | val_loss=0.8734 | val_auc=0.9522 | val_sens=0.8068 | val_spec=0.9430 | val_f1=0.7798 | best_epoch=16

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 017 | train_loss=0.0498 | val_loss=0.8231 | val_auc=0.9534 | val_sens=0.8156 | val_spec=0.9327 | val_f1=0.7675 | best_epoch=17

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 018 | train_loss=0.0545 | val_loss=0.8388 | val_auc=0.9529 | val_sens=0.8083 | val_spec=0.9430 | val_f1=0.7806 | best_epoch=17

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 019 | train_loss=0.0376 | val_loss=0.8661 | val_auc=0.9526 | val_sens=0.8009 | val_spec=0.9423 | val_f1=0.7752 | best_epoch=17

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 020 | train_loss=0.0364 | val_loss=0.8460 | val_auc=0.9525 | val_sens=0.8215 | val_spec=0.9331 | val_f1=0.7715 | best_epoch=17
Early stopping at epoch 20.

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Test metrics:
  roc_auc: 0.9561
  auprc: 0.8560
  accuracy: 0.9145
  precision: 0.7325
  recall_sensitivity: 0.8201
  specificity: 0.9350
  f1: 0.7738

==========================================================================================
Starting experiment: convnext_tiny_bce
{'name': 'convnext_tiny_bce', 'model_key': 'convnext_tiny', 'loss_name': 'bce', 'weighted_sampler': False, 'pretrained': True}
Trainable parameters: 27,820,897

/tmp/ipykernel_1467851/2574245648.py:73: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler(enabled=config["training"].get("use_amp", True) and DEVICE.type == "cuda")
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 001 | train_loss=0.4702 | val_loss=0.4477 | val_auc=0.6927 | val_sens=0.0000 | val_spec=1.0000 | val_f1=0.0000 | best_epoch=1

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 002 | train_loss=0.4244 | val_loss=0.3988 | val_auc=0.7719 | val_sens=0.0000 | val_spec=1.0000 | val_f1=0.0000 | best_epoch=2

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 003 | train_loss=0.4091 | val_loss=0.4032 | val_auc=0.7713 | val_sens=0.0914 | val_spec=0.9910 | val_f1=0.1615 | best_epoch=2

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 004 | train_loss=0.3994 | val_loss=0.4000 | val_auc=0.7669 | val_sens=0.2183 | val_spec=0.9673 | val_f1=0.3190 | best_epoch=2

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 005 | train_loss=0.3939 | val_loss=0.3913 | val_auc=0.7872 | val_sens=0.0900 | val_spec=0.9952 | val_f1=0.1618 | best_epoch=5

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 006 | train_loss=0.3878 | val_loss=0.3786 | val_auc=0.7947 | val_sens=0.2375 | val_spec=0.9712 | val_f1=0.3466 | best_epoch=6

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 007 | train_loss=0.3819 | val_loss=0.3922 | val_auc=0.7833 | val_sens=0.1504 | val_spec=0.9840 | val_f1=0.2458 | best_epoch=6

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 008 | train_loss=0.3802 | val_loss=0.3799 | val_auc=0.8055 | val_sens=0.1239 | val_spec=0.9923 | val_f1=0.2137 | best_epoch=8

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 009 | train_loss=0.3743 | val_loss=0.3711 | val_auc=0.8038 | val_sens=0.3038 | val_spec=0.9580 | val_f1=0.4059 | best_epoch=8

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 010 | train_loss=0.3697 | val_loss=0.3638 | val_auc=0.8108 | val_sens=0.2463 | val_spec=0.9747 | val_f1=0.3615 | best_epoch=10

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 011 | train_loss=0.3631 | val_loss=0.3591 | val_auc=0.8194 | val_sens=0.2360 | val_spec=0.9811 | val_f1=0.3567 | best_epoch=11

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 012 | train_loss=0.3626 | val_loss=0.3581 | val_auc=0.8162 | val_sens=0.2891 | val_spec=0.9673 | val_f1=0.4016 | best_epoch=11

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 013 | train_loss=0.3557 | val_loss=0.3565 | val_auc=0.8235 | val_sens=0.2507 | val_spec=0.9840 | val_f1=0.3786 | best_epoch=13

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 014 | train_loss=0.3513 | val_loss=0.3494 | val_auc=0.8312 | val_sens=0.2434 | val_spec=0.9843 | val_f1=0.3700 | best_epoch=14

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 015 | train_loss=0.3460 | val_loss=0.3494 | val_auc=0.8334 | val_sens=0.2566 | val_spec=0.9789 | val_f1=0.3791 | best_epoch=15

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 016 | train_loss=0.3387 | val_loss=0.3446 | val_auc=0.8347 | val_sens=0.3083 | val_spec=0.9718 | val_f1=0.4287 | best_epoch=16

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 017 | train_loss=0.3366 | val_loss=0.3421 | val_auc=0.8402 | val_sens=0.3260 | val_spec=0.9667 | val_f1=0.4407 | best_epoch=17

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 018 | train_loss=0.3321 | val_loss=0.3410 | val_auc=0.8403 | val_sens=0.3451 | val_spec=0.9648 | val_f1=0.4579 | best_epoch=18

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 019 | train_loss=0.3290 | val_loss=0.3395 | val_auc=0.8427 | val_sens=0.2979 | val_spec=0.9747 | val_f1=0.4213 | best_epoch=19

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 020 | train_loss=0.3253 | val_loss=0.3389 | val_auc=0.8428 | val_sens=0.3289 | val_spec=0.9693 | val_f1=0.4473 | best_epoch=20

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Test metrics:
  roc_auc: 0.8581
  auprc: 0.6362
  accuracy: 0.8621
  precision: 0.7225
  recall_sensitivity: 0.3687
  specificity: 0.9693
  f1: 0.4883

==========================================================================================
Starting experiment: convnext_tiny_weighted_bce
{'name': 'convnext_tiny_weighted_bce', 'model_key': 'convnext_tiny', 'loss_name': 'weighted_bce', 'weighted_sampler': False, 'pretrained': True}
Trainable parameters: 27,820,897
Using weighted BCE pos_weight=4.6004

/tmp/ipykernel_1467851/2574245648.py:73: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler(enabled=config["training"].get("use_amp", True) and DEVICE.type == "cuda")
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 001 | train_loss=1.0828 | val_loss=1.0426 | val_auc=0.7651 | val_sens=0.4056 | val_spec=0.8831 | val_f1=0.4173 | best_epoch=1

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 002 | train_loss=0.9789 | val_loss=0.8842 | val_auc=0.7966 | val_sens=0.7493 | val_spec=0.6685 | val_f1=0.4575 | best_epoch=2

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 003 | train_loss=0.9349 | val_loss=0.9137 | val_auc=0.7925 | val_sens=0.5855 | val_spec=0.8088 | val_f1=0.4749 | best_epoch=2

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 004 | train_loss=0.9183 | val_loss=0.9090 | val_auc=0.7913 | val_sens=0.8378 | val_spec=0.5698 | val_f1=0.4388 | best_epoch=2

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 005 | train_loss=0.9010 | val_loss=0.9903 | val_auc=0.7735 | val_sens=0.7876 | val_spec=0.5993 | val_f1=0.4336 | best_epoch=2
Early stopping at epoch 5.

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Test metrics:
  roc_auc: 0.8158
  auprc: 0.5146
  accuracy: 0.6971
  precision: 0.3453
  recall_sensitivity: 0.7788
  specificity: 0.6794
  f1: 0.4785

==========================================================================================
Starting experiment: convnext_tiny_focal
{'name': 'convnext_tiny_focal', 'model_key': 'convnext_tiny', 'loss_name': 'focal', 'weighted_sampler': False, 'pretrained': True}
Trainable parameters: 27,820,897

/tmp/ipykernel_1467851/2574245648.py:73: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler(enabled=config["training"].get("use_amp", True) and DEVICE.type == "cuda")
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 001 | train_loss=0.0554 | val_loss=0.0388 | val_auc=0.7737 | val_sens=0.0000 | val_spec=1.0000 | val_f1=0.0000 | best_epoch=1

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 002 | train_loss=0.0399 | val_loss=0.0372 | val_auc=0.7990 | val_sens=0.0029 | val_spec=1.0000 | val_f1=0.0059 | best_epoch=2

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 003 | train_loss=0.0388 | val_loss=0.0393 | val_auc=0.7824 | val_sens=0.0000 | val_spec=1.0000 | val_f1=0.0000 | best_epoch=2

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 004 | train_loss=0.0379 | val_loss=0.0368 | val_auc=0.8032 | val_sens=0.0487 | val_spec=0.9984 | val_f1=0.0922 | best_epoch=4

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 005 | train_loss=0.0368 | val_loss=0.0370 | val_auc=0.8231 | val_sens=0.1283 | val_spec=0.9955 | val_f1=0.2234 | best_epoch=5

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 006 | train_loss=0.0364 | val_loss=0.0361 | val_auc=0.8252 | val_sens=0.0708 | val_spec=0.9984 | val_f1=0.1313 | best_epoch=6

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 007 | train_loss=0.0357 | val_loss=0.0366 | val_auc=0.8345 | val_sens=0.2522 | val_spec=0.9859 | val_f1=0.3830 | best_epoch=7

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 008 | train_loss=0.0344 | val_loss=0.0343 | val_auc=0.8453 | val_sens=0.1121 | val_spec=0.9990 | val_f1=0.2008 | best_epoch=8

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 009 | train_loss=0.0339 | val_loss=0.0333 | val_auc=0.8538 | val_sens=0.1962 | val_spec=0.9946 | val_f1=0.3213 | best_epoch=9

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 010 | train_loss=0.0331 | val_loss=0.0356 | val_auc=0.8444 | val_sens=0.1150 | val_spec=0.9987 | val_f1=0.2053 | best_epoch=9

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 011 | train_loss=0.0320 | val_loss=0.0317 | val_auc=0.8646 | val_sens=0.1873 | val_spec=0.9965 | val_f1=0.3113 | best_epoch=11

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 012 | train_loss=0.0307 | val_loss=0.0316 | val_auc=0.8672 | val_sens=0.2257 | val_spec=0.9923 | val_f1=0.3579 | best_epoch=12

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 013 | train_loss=0.0295 | val_loss=0.0303 | val_auc=0.8815 | val_sens=0.2965 | val_spec=0.9939 | val_f1=0.4477 | best_epoch=13

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 014 | train_loss=0.0276 | val_loss=0.0307 | val_auc=0.8806 | val_sens=0.2021 | val_spec=0.9974 | val_f1=0.3329 | best_epoch=13

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 015 | train_loss=0.0257 | val_loss=0.0299 | val_auc=0.8901 | val_sens=0.3437 | val_spec=0.9888 | val_f1=0.4926 | best_epoch=15

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 016 | train_loss=0.0236 | val_loss=0.0290 | val_auc=0.8951 | val_sens=0.4012 | val_spec=0.9865 | val_f1=0.5484 | best_epoch=16

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 017 | train_loss=0.0218 | val_loss=0.0282 | val_auc=0.8991 | val_sens=0.4012 | val_spec=0.9878 | val_f1=0.5506 | best_epoch=17

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 018 | train_loss=0.0196 | val_loss=0.0307 | val_auc=0.8970 | val_sens=0.4174 | val_spec=0.9865 | val_f1=0.5643 | best_epoch=17

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 019 | train_loss=0.0179 | val_loss=0.0296 | val_auc=0.9058 | val_sens=0.4307 | val_spec=0.9846 | val_f1=0.5737 | best_epoch=19

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 020 | train_loss=0.0168 | val_loss=0.0309 | val_auc=0.9057 | val_sens=0.4631 | val_spec=0.9785 | val_f1=0.5930 | best_epoch=19

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Test metrics:
  roc_auc: 0.9243
  auprc: 0.7850
  accuracy: 0.8934
  precision: 0.8719
  recall_sensitivity: 0.4720
  specificity: 0.9849
  f1: 0.6124

==========================================================================================
Starting experiment: convnext_tiny_cb_focal
{'name': 'convnext_tiny_cb_focal', 'model_key': 'convnext_tiny', 'loss_name': 'class_balanced_focal', 'weighted_sampler': False, 'pretrained': True}
Trainable parameters: 27,820,897

/tmp/ipykernel_1467851/2574245648.py:73: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler(enabled=config["training"].get("use_amp", True) and DEVICE.type == "cuda")
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 001 | train_loss=0.1339 | val_loss=0.1030 | val_auc=0.7508 | val_sens=0.2625 | val_spec=0.9292 | val_f1=0.3305 | best_epoch=1

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 002 | train_loss=0.1040 | val_loss=0.0983 | val_auc=0.7678 | val_sens=0.4543 | val_spec=0.8581 | val_f1=0.4311 | best_epoch=2

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 003 | train_loss=0.1004 | val_loss=0.1013 | val_auc=0.7727 | val_sens=0.2345 | val_spec=0.9644 | val_f1=0.3354 | best_epoch=3

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 004 | train_loss=0.0987 | val_loss=0.0951 | val_auc=0.7846 | val_sens=0.6136 | val_spec=0.7889 | val_f1=0.4746 | best_epoch=4

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 005 | train_loss=0.0966 | val_loss=0.1018 | val_auc=0.7626 | val_sens=0.2522 | val_spec=0.9532 | val_f1=0.3437 | best_epoch=4

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 006 | train_loss=0.0966 | val_loss=0.0931 | val_auc=0.7847 | val_sens=0.5162 | val_spec=0.8527 | val_f1=0.4704 | best_epoch=6

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 007 | train_loss=0.0954 | val_loss=0.0929 | val_auc=0.7920 | val_sens=0.5752 | val_spec=0.8254 | val_f1=0.4836 | best_epoch=7

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 008 | train_loss=0.0943 | val_loss=0.0917 | val_auc=0.7979 | val_sens=0.4381 | val_spec=0.9074 | val_f1=0.4699 | best_epoch=8

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 009 | train_loss=0.0929 | val_loss=0.0897 | val_auc=0.8077 | val_sens=0.5782 | val_spec=0.8328 | val_f1=0.4925 | best_epoch=9

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 010 | train_loss=0.0917 | val_loss=0.0899 | val_auc=0.8009 | val_sens=0.5457 | val_spec=0.8629 | val_f1=0.5014 | best_epoch=9

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 011 | train_loss=0.0913 | val_loss=0.0912 | val_auc=0.8167 | val_sens=0.3628 | val_spec=0.9552 | val_f1=0.4624 | best_epoch=11

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 012 | train_loss=0.0895 | val_loss=0.0885 | val_auc=0.8135 | val_sens=0.5472 | val_spec=0.8661 | val_f1=0.5058 | best_epoch=11

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 013 | train_loss=0.0896 | val_loss=0.0878 | val_auc=0.8155 | val_sens=0.5383 | val_spec=0.8802 | val_f1=0.5152 | best_epoch=11

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 014 | train_loss=0.0873 | val_loss=0.0858 | val_auc=0.8269 | val_sens=0.5590 | val_spec=0.8799 | val_f1=0.5293 | best_epoch=14

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 015 | train_loss=0.0865 | val_loss=0.0854 | val_auc=0.8245 | val_sens=0.5516 | val_spec=0.8863 | val_f1=0.5316 | best_epoch=14

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 016 | train_loss=0.0850 | val_loss=0.0840 | val_auc=0.8311 | val_sens=0.5796 | val_spec=0.8722 | val_f1=0.5347 | best_epoch=16

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 017 | train_loss=0.0838 | val_loss=0.0837 | val_auc=0.8338 | val_sens=0.5811 | val_spec=0.8619 | val_f1=0.5243 | best_epoch=17

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 018 | train_loss=0.0831 | val_loss=0.0842 | val_auc=0.8330 | val_sens=0.5369 | val_spec=0.8949 | val_f1=0.5314 | best_epoch=17

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 019 | train_loss=0.0817 | val_loss=0.0838 | val_auc=0.8354 | val_sens=0.5265 | val_spec=0.9071 | val_f1=0.5389 | best_epoch=19

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 020 | train_loss=0.0815 | val_loss=0.0832 | val_auc=0.8353 | val_sens=0.5796 | val_spec=0.8728 | val_f1=0.5354 | best_epoch=19

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Test metrics:
  roc_auc: 0.8572
  auprc: 0.6302
  accuracy: 0.8511
  precision: 0.5848
  recall_sensitivity: 0.5693
  specificity: 0.9122
  f1: 0.5770

==========================================================================================
Starting experiment: convnext_tiny_weighted_bce_sampler
{'name': 'convnext_tiny_weighted_bce_sampler', 'model_key': 'convnext_tiny', 'loss_name': 'weighted_bce', 'weighted_sampler': True, 'pretrained': True}
Trainable parameters: 27,820,897
Using weighted BCE pos_weight=4.6004

/tmp/ipykernel_1467851/2574245648.py:73: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler(enabled=config["training"].get("use_amp", True) and DEVICE.type == "cuda")
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 001 | train_loss=1.2926 | val_loss=1.4338 | val_auc=0.7619 | val_sens=0.9985 | val_spec=0.0756 | val_f1=0.3193 | best_epoch=1

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 002 | train_loss=1.1368 | val_loss=1.1820 | val_auc=0.7813 | val_sens=0.9823 | val_spec=0.2543 | val_f1=0.3627 | best_epoch=2

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 003 | train_loss=1.0962 | val_loss=1.0043 | val_auc=0.7837 | val_sens=0.9690 | val_spec=0.2761 | val_f1=0.3655 | best_epoch=3

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 004 | train_loss=1.0911 | val_loss=1.2428 | val_auc=0.7873 | val_sens=0.9941 | val_spec=0.1960 | val_f1=0.3490 | best_epoch=4

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 005 | train_loss=1.0463 | val_loss=1.6581 | val_auc=0.7920 | val_sens=1.0000 | val_spec=0.1390 | val_f1=0.3353 | best_epoch=5

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 006 | train_loss=1.0584 | val_loss=1.0510 | val_auc=0.7941 | val_sens=0.9912 | val_spec=0.2303 | val_f1=0.3581 | best_epoch=6

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 007 | train_loss=1.0421 | val_loss=1.0696 | val_auc=0.8005 | val_sens=0.9779 | val_spec=0.3113 | val_f1=0.3798 | best_epoch=7

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 008 | train_loss=1.0199 | val_loss=1.1865 | val_auc=0.8151 | val_sens=0.9926 | val_spec=0.2559 | val_f1=0.3664 | best_epoch=8

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 009 | train_loss=1.0108 | val_loss=1.2053 | val_auc=0.8159 | val_sens=0.9971 | val_spec=0.2152 | val_f1=0.3554 | best_epoch=9

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 010 | train_loss=1.0179 | val_loss=0.9779 | val_auc=0.8160 | val_sens=0.9676 | val_spec=0.3594 | val_f1=0.3935 | best_epoch=10

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 011 | train_loss=0.9871 | val_loss=1.3840 | val_auc=0.7967 | val_sens=0.9985 | val_spec=0.1951 | val_f1=0.3501 | best_epoch=10

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 012 | train_loss=0.9810 | val_loss=1.1120 | val_auc=0.8263 | val_sens=0.9882 | val_spec=0.2703 | val_f1=0.3696 | best_epoch=12

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 013 | train_loss=0.9658 | val_loss=1.0504 | val_auc=0.8243 | val_sens=0.9794 | val_spec=0.3206 | val_f1=0.3835 | best_epoch=12

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 014 | train_loss=0.9436 | val_loss=1.0352 | val_auc=0.8284 | val_sens=0.9661 | val_spec=0.3700 | val_f1=0.3970 | best_epoch=14

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 015 | train_loss=0.9160 | val_loss=1.0397 | val_auc=0.8374 | val_sens=0.9690 | val_spec=0.3719 | val_f1=0.3987 | best_epoch=15

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 016 | train_loss=0.8896 | val_loss=1.0738 | val_auc=0.8386 | val_sens=0.9646 | val_spec=0.3674 | val_f1=0.3955 | best_epoch=16

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 017 | train_loss=0.8836 | val_loss=1.0089 | val_auc=0.8431 | val_sens=0.9602 | val_spec=0.4218 | val_f1=0.4154 | best_epoch=17

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 018 | train_loss=0.8622 | val_loss=1.0265 | val_auc=0.8444 | val_sens=0.9617 | val_spec=0.4228 | val_f1=0.4163 | best_epoch=18

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 019 | train_loss=0.8390 | val_loss=1.0401 | val_auc=0.8458 | val_sens=0.9631 | val_spec=0.4215 | val_f1=0.4163 | best_epoch=19

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):
/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Epoch 020 | train_loss=0.8391 | val_loss=1.0343 | val_auc=0.8468 | val_sens=0.9602 | val_spec=0.4266 | val_f1=0.4174 | best_epoch=20

/tmp/ipykernel_1467851/2574245648.py:18: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=use_amp):

Test metrics:
  roc_auc: 0.8592
  auprc: 0.6222
  accuracy: 0.5313
  precision: 0.2713
  recall_sensitivity: 0.9646
  specificity: 0.4372
  f1: 0.4234

Final summary saved to: content/skin_cancer_outputs/results/all_experiments_summary.csv

,experiment_name,model_key,loss_name,weighted_sampler,best_epoch,best_val_score,test_loss,test_predictions_path,checkpoint_path,log_path,...,test_auprc,test_accuracy,test_precision,test_recall_sensitivity,test_f1,test_specificity,test_tn,test_fp,test_fn,test_tp
0,effb0_bce,efficientnet_b0,bce,False,20,0.947306,0.314987,content/skin_cancer_outputs/results/effb0_bce_...,content/skin_cancer_outputs/checkpoints/effb0_...,content/skin_cancer_outputs/logs/effb0_bce_tra...,...,0.871683,0.927895,0.841216,0.734513,0.784252,0.969891,3028,94,180,498
1,effb0_weighted_bce,efficientnet_b0,weighted_bce,False,20,0.946635,0.861348,content/skin_cancer_outputs/results/effb0_weig...,content/skin_cancer_outputs/checkpoints/effb0_...,content/skin_cancer_outputs/logs/effb0_weighte...,...,0.869617,0.924474,0.789630,0.786136,0.787879,0.954516,2980,142,145,533
2,effb0_focal,efficientnet_b0,focal,False,18,0.930979,0.029409,content/skin_cancer_outputs/results/effb0_foca...,content/skin_cancer_outputs/checkpoints/effb0_...,content/skin_cancer_outputs/logs/effb0_focal_t...,...,0.821625,0.910526,0.840726,0.615044,0.710392,0.974696,3043,79,261,417
3,effb0_cb_focal,efficientnet_b0,class_balanced_focal,False,18,0.936626,0.085014,content/skin_cancer_outputs/results/effb0_cb_f...,content/skin_cancer_outputs/checkpoints/effb0_...,content/skin_cancer_outputs/logs/effb0_cb_foca...,...,0.830261,0.902368,0.712310,0.759587,0.735189,0.933376,2914,208,163,515
4,effb0_weighted_bce_sampler,efficientnet_b0,weighted_bce,True,17,0.953362,0.797490,content/skin_cancer_outputs/results/effb0_weig...,content/skin_cancer_outputs/checkpoints/effb0_...,content/skin_cancer_outputs/logs/effb0_weighte...,...,0.856032,0.914474,0.732543,0.820059,0.773834,0.934978,2919,203,122,556
5,convnext_tiny_bce,convnext_tiny,bce,False,20,0.842794,0.322216,content/skin_cancer_outputs/results/convnext_t...,content/skin_cancer_outputs/checkpoints/convne...,content/skin_cancer_outputs/logs/convnext_tiny...,...,0.636198,0.862105,0.722543,0.368732,0.488281,0.969250,3026,96,428,250
6,convnext_tiny_weighted_bce,convnext_tiny,weighted_bce,False,2,0.796640,0.849572,content/skin_cancer_outputs/results/convnext_t...,content/skin_cancer_outputs/checkpoints/convne...,content/skin_cancer_outputs/logs/convnext_tiny...,...,0.514554,0.697105,0.345324,0.778761,0.478478,0.679372,2121,1001,150,528
7,convnext_tiny_focal,convnext_tiny,focal,False,19,0.905842,0.027115,content/skin_cancer_outputs/results/convnext_t...,content/skin_cancer_outputs/checkpoints/convne...,content/skin_cancer_outputs/logs/convnext_tiny...,...,0.785025,0.893421,0.871935,0.471976,0.612440,0.984946,3075,47,358,320
8,convnext_tiny_cb_focal,convnext_tiny,class_balanced_focal,False,19,0.835432,0.079906,content/skin_cancer_outputs/results/convnext_t...,content/skin_cancer_outputs/checkpoints/convne...,content/skin_cancer_outputs/logs/convnext_tiny...,...,0.630196,0.851053,0.584848,0.569322,0.576981,0.912236,2848,274,292,386
9,convnext_tiny_weighted_bce_sampler,convnext_tiny,weighted_bce,True,20,0.846785,0.986816,content/skin_cancer_outputs/results/convnext_t...,content/skin_cancer_outputs/checkpoints/convne...,content/skin_cancer_outputs/logs/convnext_tiny...,...,0.622185,0.531316,0.271257,0.964602,0.423438,0.437220,1365,1757,24,654

## 12. Select best model and create paper-ready final table

The best model is selected by **test ROC-AUC** for reporting convenience here. In the paper, emphasize that model selection during training used **validation ROC-AUC**.

In [14]:
if len(summary_df) == 0:
    raise RuntimeError("No successful experiments. Check failed_experiments.csv and error messages above.")

ranking_cols = [
    "experiment_name", "model_key", "loss_name", "weighted_sampler", "best_epoch",
    "test_roc_auc", "test_auprc", "test_accuracy", "test_precision",
    "test_recall_sensitivity", "test_specificity", "test_f1", "test_tn", "test_fp", "test_fn", "test_tp",
]
existing_cols = [c for c in ranking_cols if c in summary_df.columns]
final_table = summary_df[existing_cols].sort_values("test_roc_auc", ascending=False).reset_index(drop=True)
final_table_path = RESULT_DIR / "paper_results_table.csv"
final_table.to_csv(final_table_path, index=False)

best_row = final_table.iloc[0].to_dict()
best_experiment_name = best_row["experiment_name"]
print("Best experiment by test ROC-AUC:", best_experiment_name)
print("Paper results table saved to:", final_table_path)
final_table

Best experiment by test ROC-AUC: effb0_weighted_bce
Paper results table saved to: content/skin_cancer_outputs/results/paper_results_table.csv

,experiment_name,model_key,loss_name,weighted_sampler,best_epoch,test_roc_auc,test_auprc,test_accuracy,test_precision,test_recall_sensitivity,test_specificity,test_f1,test_tn,test_fp,test_fn,test_tp
0,effb0_weighted_bce,efficientnet_b0,weighted_bce,False,20,0.957570,0.869617,0.924474,0.789630,0.786136,0.954516,0.787879,2980,142,145,533
1,effb0_bce,efficientnet_b0,bce,False,20,0.957260,0.871683,0.927895,0.841216,0.734513,0.969891,0.784252,3028,94,180,498
2,effb0_weighted_bce_sampler,efficientnet_b0,weighted_bce,True,17,0.956071,0.856032,0.914474,0.732543,0.820059,0.934978,0.773834,2919,203,122,556
3,effb0_cb_focal,efficientnet_b0,class_balanced_focal,False,18,0.939280,0.830261,0.902368,0.712310,0.759587,0.933376,0.735189,2914,208,163,515
4,effb0_focal,efficientnet_b0,focal,False,18,0.939136,0.821625,0.910526,0.840726,0.615044,0.974696,0.710392,3043,79,261,417
5,convnext_tiny_focal,convnext_tiny,focal,False,19,0.924313,0.785025,0.893421,0.871935,0.471976,0.984946,0.612440,3075,47,358,320
6,convnext_tiny_weighted_bce_sampler,convnext_tiny,weighted_bce,True,20,0.859213,0.622185,0.531316,0.271257,0.964602,0.437220,0.423438,1365,1757,24,654
7,convnext_tiny_bce,convnext_tiny,bce,False,20,0.858091,0.636198,0.862105,0.722543,0.368732,0.969250,0.488281,3026,96,428,250
8,convnext_tiny_cb_focal,convnext_tiny,class_balanced_focal,False,19,0.857185,0.630196,0.851053,0.584848,0.569322,0.912236,0.576981,2848,274,292,386
9,convnext_tiny_weighted_bce,convnext_tiny,weighted_bce,False,2,0.815845,0.514554,0.697105,0.345324,0.778761,0.679372,0.478478,2121,1001,150,528

## 13. Optional Grad-CAM for the best model

This cell creates Grad-CAM visualizations for a few test images using the best experiment's checkpoint. It is optional and will be skipped if the Grad-CAM package or model layer discovery fails.

In [15]:
def denormalize_tensor(img_tensor: torch.Tensor) -> np.ndarray:
    img = img_tensor.detach().cpu().clone()
    mean = torch.tensor(IMAGENET_MEAN).view(3, 1, 1)
    std = torch.tensor(IMAGENET_STD).view(3, 1, 1)
    img = img * std + mean
    img = img.clamp(0, 1)
    return img.permute(1, 2, 0).numpy()


def get_gradcam_target_layer(model: nn.Module):
    # Common timm structures.
    if hasattr(model, "conv_head"):
        return model.conv_head
    if hasattr(model, "stages"):
        return model.stages[-1]
    if hasattr(model, "blocks"):
        return model.blocks[-1]
    # Fallback: last Conv2d module.
    last_conv = None
    for module in model.modules():
        if isinstance(module, nn.Conv2d):
            last_conv = module
    if last_conv is None:
        raise ValueError("Could not find a convolutional layer for Grad-CAM.")
    return last_conv


def make_gradcam_for_best_model(best_row: Dict, test_df: pd.DataFrame, config: Dict, n_images: int = 8):
    if not config["run"].get("make_gradcam", True):
        print("Grad-CAM disabled in config.")
        return
    try:
        from pytorch_grad_cam import GradCAM
        from pytorch_grad_cam.utils.image import show_cam_on_image
        from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget
    except Exception as e:
        print("Skipping Grad-CAM because pytorch-grad-cam is unavailable:", repr(e))
        return

    exp_name = best_row["experiment_name"]
    exp_record = summary_df[summary_df["experiment_name"] == exp_name].iloc[0].to_dict()
    checkpoint = torch.load(exp_record["checkpoint_path"], map_location=DEVICE, weights_only=False)
    exp = checkpoint["experiment"]

    model = build_model(exp["model_key"], pretrained=False).to(DEVICE)
    model.load_state_dict(checkpoint["model_state_dict"])
    model.eval()

    target_layer = get_gradcam_target_layer(model)
    transform = get_transforms("val", config)

    # Sample malignant cases first because they are clinically important; fill with benign if needed.
    malignant_df = test_df[test_df["target"] == 1]
    benign_df = test_df[test_df["target"] == 0]
    sample_df = pd.concat([
        malignant_df.sample(min(len(malignant_df), n_images // 2), random_state=config["seed"]),
        benign_df.sample(min(len(benign_df), n_images - min(len(malignant_df), n_images // 2)), random_state=config["seed"]),
    ]).reset_index(drop=True)

    out_dir = FIGURE_DIR / "gradcam_best_model"
    out_dir.mkdir(parents=True, exist_ok=True)

    with GradCAM(model=model, target_layers=[target_layer]) as cam:
        for i, row in sample_df.iterrows():
            image_path = row["image_path"]
            pil_img = Image.open(image_path).convert("RGB")
            input_tensor = transform(pil_img).unsqueeze(0).to(DEVICE)
            with torch.no_grad():
                logit = model(input_tensor).view(-1)
                prob = torch.sigmoid(logit).item()
            grayscale_cam = cam(input_tensor=input_tensor, targets=[ClassifierOutputTarget(0)])[0]
            rgb_img = denormalize_tensor(input_tensor[0])
            visualization = show_cam_on_image(rgb_img, grayscale_cam, use_rgb=True)

            save_path = out_dir / f"gradcam_{i:02d}_true{int(row['target'])}_prob{prob:.3f}.png"
            plt.figure(figsize=(8, 4))
            plt.subplot(1, 2, 1)
            plt.imshow(rgb_img)
            plt.axis("off")
            plt.title(f"Original | true={int(row['target'])}")
            plt.subplot(1, 2, 2)
            plt.imshow(visualization)
            plt.axis("off")
            plt.title(f"Grad-CAM | p(malignant)={prob:.3f}")
            plt.tight_layout()
            plt.savefig(save_path, dpi=300)
            plt.close()
            print("Saved:", save_path)

make_gradcam_for_best_model(best_row, test_df, CONFIG, n_images=8)

Saved: content/skin_cancer_outputs/figures/gradcam_best_model/gradcam_00_true1_prob0.352.png
Saved: content/skin_cancer_outputs/figures/gradcam_best_model/gradcam_01_true1_prob0.998.png
Saved: content/skin_cancer_outputs/figures/gradcam_best_model/gradcam_02_true1_prob0.560.png
Saved: content/skin_cancer_outputs/figures/gradcam_best_model/gradcam_03_true1_prob1.000.png
Saved: content/skin_cancer_outputs/figures/gradcam_best_model/gradcam_04_true0_prob0.000.png
Saved: content/skin_cancer_outputs/figures/gradcam_best_model/gradcam_05_true0_prob0.020.png
Saved: content/skin_cancer_outputs/figures/gradcam_best_model/gradcam_06_true0_prob0.000.png
Saved: content/skin_cancer_outputs/figures/gradcam_best_model/gradcam_07_true0_prob0.032.png

## 14. What to use in the paper

After the notebook finishes, use these files:

- `outputs/results/paper_results_table.csv`: main quantitative results table
- `outputs/results/all_experiments_summary.csv`: complete metrics for all experiments
- `outputs/logs/*_training_log.csv`: per-epoch training logs
- `outputs/figures/*_roc.png`: per-experiment ROC curves
- `outputs/figures/combined_test_roc.png`: model comparison ROC figure
- `outputs/figures/*_confusion_matrix.png`: confusion matrices
- `outputs/figures/*_training_curves.png`: training curves
- `outputs/figures/gradcam_best_model/*.png`: explainability examples

Recommended paper framing:

1. Model comparison: EfficientNet vs ConvNeXt.
2. Imbalance comparison: BCE vs weighted BCE vs focal loss vs class-balanced focal loss vs weighted sampling.
3. Main clinical emphasis: ROC-AUC, sensitivity/recall, specificity, and confusion matrix.
4. Do not claim clinical deployment; describe this as a retrospective image-classification experiment.